version: "3.2"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: yee
        USER_PASSWORD: yee
    image: yee/dev:latest
    volumes:
      - ./spacemacs:$HOME/.spacemacs:rw
      - ./emacs/spacemacs.d:$HOME/.emacs.d:rw
      - ./emacs.d/private:$HOME/.emacs.d/private:rw
      - ./zshrc:$HOME/.zshrc:rw
      - ./gitconfig:$HOME/.gitconfig:rw
      - ./gitignore:$HOME/.gitignore:rw
      - ./clang-format:$HOME/.clang-format:rw
      - ./vimrc:$HOME/.vimrc:rw
      - ./tmux.conf:$HOME/.tmux.conf:rw
      - ./tmux/plugins:$HOME/.tmux/plugins:rw
      - ./ssh:$HOME/.ssh:rw
      - ./oh-my-zsh/custom:$HOME/.oh-my-zsh/custom
      - /mnt/Workspace:$HOME/Workspace:rw
    entrypoint: ["/bin/zsh"]
