version: "3.2"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   USER_NAME: yee
      #   USER_PASSWORD: yee
    image: yee/dev:latest
    volumes:
      - ./spacemacs:/home/root/.spacemacs:rw
      - ./emacs/spacemacs.d:/home/root/.emacs.d:rw
      - ./emacs.d/private:/home/root/.emacs.d/private:rw
      - ./zshrc:/home/root/.zshrc:rw
      - ./gitconfig:/home/root/.gitconfig:rw
      - ./gitignore:/home/root/.gitignore:rw
      - ./clang-format:/home/root/.clang-format:rw
      - ./vimrc:/home/root/.vimrc:rw
      - ./tmux.conf:/home/root/.tmux.conf:rw
      - ./tmux/plugins:/home/root/.tmux/plugins:rw
      - ./ssh:/home/root/.ssh:rw
      - ./oh-my-zsh/custom:/home/root/.oh-my-zsh/custom
      # - /mnt/Workspace:/home/root/Workspace:rw
    entrypoint: ["/bin/zsh"]
