
CLION_VERSION=2016.3.2
IDEA_VERSION=145.972.3

TOOLS_DIR=$HOME/tools

# clion
PATH="$PATH:$TOOLS_DIR/clion-$CLION_VERSION/bin"
# IntelliJ
PATH="$PATH:$TOOLS_DIR/idea-IC-$IDEA_VERSION/bin"

export PATH
