
font:
  size: 15.0

background_opacity: 0.98

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

live_config_reload: true

mouse:
  url:
    # Command
    modifiers: None

key_bindings:
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-334790547
  - { key: F,  mods: Alt,           chars: "\x1bf"                       }
  - { key: B,  mods: Alt,           chars: "\x1bb"                       }
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-427592040
  - { key: D,  mods: Alt,           chars: "\x1bd"                       }
