
font:
  size: 15.0

# background_opacity: 0.98
window:
  opacity: 0.95

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

live_config_reload: true

mouse:
  hints:
    # Command
    modifiers: None

key_bindings:
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-334790547
  - { key: F,  mods: Alt,           chars: "\x1bf"                       }
  - { key: B,  mods: Alt,           chars: "\x1bb"                       }
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-427592040
  - { key: D,  mods: Alt,           chars: "\x1bd"                       }
  - { key: X,  mods: Alt,           chars: "\x1bx"                       }
  - { key: Tab,   mods: None,       chars: "\x09" }
  - { key: I,     mods: Control,    chars: "\x1b[105;5u" }
