
font:
  size: 15.0

background_opacity: 0.98

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

live_config_reload: true

mouse:
  url:
    # Command
    modifiers: None
